spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
    driverClassName: org.postgresql.Driver


  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none

  liquibase:
    changeLog: classpath:master.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 1